name: Deploy Frontend and Backend to GCP Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Build and Push Docker image for Backend to Artifact Registry
        run: |
          docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-repo/openai-backend:$GITHUB_SHA -f ./openai_backend/Dockerfile .
          docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-repo/openai-backend:$GITHUB_SHA

      - name: Deploy Backend to Cloud Run
        id: deploy-backend
        run: |
          gcloud run deploy openai-backend-service \
            --image us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-repo/openai-backend:$GITHUB_SHA \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --set-env-vars OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
            --format=json > backend-deployment-output.json

      - name: Extract Backend URL
        id: backend-url
        run: |
          BACKEND_URL=$(cat backend-deployment-output.json | jq -r '.status.url')
          echo "BACKEND_URL=${BACKEND_URL}" >> $GITHUB_ENV

  deploy-frontend:
    needs: deploy-backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Modify Frontend to Use Backend URL
        run: |
          sed -i "s|REPLACE_WITH_BACKEND_URL|${{ env.BACKEND_URL }}|g" ./openai_frontend/script.js

      - name: Build and Push Docker image for Frontend to Artifact Registry
        run: |
          docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-repo/openai-frontend:$GITHUB_SHA -f ./openai_frontend/Dockerfile .
          docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-repo/openai-frontend:$GITHUB_SHA

      - name: Deploy Frontend to Cloud Run
        run: |
          gcloud run deploy openai-frontend-service \
            --image us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-repo/openai-frontend:$GITHUB_SHA \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
